# Only build tags
# if: tag IS present

language: java

before_script:
  - "mkdir $HOME/lambda"

jdk:
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  
#after_success: "coveralls"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Ptravis"
  skip_cleanup: true
  on:
    jdk: openjdk8
    tags: true
    all_branches: true
